language: python

sudo: false

env:
  global:
    #- DEPENDS="cython>=0.19"
    - NO_NET=1

# 2.6 and "nightly" do not work at the moment, so they are commented out.
python:
  # - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.5.1"
  #- "3.5-dev" # 3.5 development branch
  # - "nightly" # currently points to 3.6-dev

# start Virtual X, so default matplotlib backend work
# before_install:
#     #- "pip install $DEPENDS"
#     - "export DISPLAY=:99.0"
#     - "sh -e /etc/init.d/xvfb start"

# # command to install dependencies
# install: "pip install -r requirements.travis.txt"

before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda/bin:$PATH
  - conda update --yes conda
  # The next couple lines fix a crash with multiprocessing on Travis and are not specific to using Miniconda
  - sudo rm -rf /dev/shm
  - sudo ln -s /run/shm /dev/shm
# Install packages
install:
  - conda install --yes python=$TRAVIS_PYTHON_VERSION numpy scipy matplotlib nose dateutil pandas


# command to run tests
script: 
    - export PYTHONPATH=$PYTHONPATH:.
    - nosetests -v -w ./pyemu/tests

after_success:
    codecov
