--wisudo: false
language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda update --yes conda
install:
  - conda install --yes python=$TRAVIS_PYTHON_VERSION pip numpy scipy pandas nose matplotlib
  - pip install coveralls
  - pip install pyshp
  - pip install git+https://github.com/modflowpy/flopy.git@develop
script:
  - export PYTHONPATH=$PYTHONPATH:.
  - nosetests -v --with-id -w ./autotest --with-coverage --cover-package=pyemu
after_success:
  - coveralls


